// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtYbDyvU0o5Wym3WcC3BcopOXiWyvSbhw',
    appId: '1:647470475554:web:a207e105923a6d03209d7b',
    messagingSenderId: '647470475554',
    projectId: 'se-todoapp',
    authDomain: 'se-todoapp.firebaseapp.com',
    databaseURL: 'https://se-todoapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'se-todoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXBZ6U1WO7sKi3CFKMRWYIxPEiicEJu3c',
    appId: '1:647470475554:android:6521de6e43322248209d7b',
    messagingSenderId: '647470475554',
    projectId: 'se-todoapp',
    databaseURL: 'https://se-todoapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'se-todoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNf7vvp28_56_km4cjyY6oF-L4HUlV_1Y',
    appId: '1:647470475554:ios:c75ef31bf3a0938b209d7b',
    messagingSenderId: '647470475554',
    projectId: 'se-todoapp',
    databaseURL: 'https://se-todoapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'se-todoapp.appspot.com',
    iosBundleId: 'com.example.FlutterProject.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNf7vvp28_56_km4cjyY6oF-L4HUlV_1Y',
    appId: '1:647470475554:ios:fcd98b88b58ca0c3209d7b',
    messagingSenderId: '647470475554',
    projectId: 'se-todoapp',
    databaseURL: 'https://se-todoapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'se-todoapp.appspot.com',
    iosBundleId: 'com.example.FlutterProject.testFlutter.RunnerTests',
  );
}
